version: "3.8"

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usersdb
    ports:
      - "3307:3306"
    volumes:
      - ./init/master.sql:/docker-entrypoint-initdb.d/master.sql
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=usersdb

  mysql-replica:
    image: mysql:8.0
    container_name: mysql-replica
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usersdb
    ports:
      - "3308:3306"
    depends_on:
      - mysql-master
    volumes:
      - ./init/replica.sh:/docker-entrypoint-initdb.d/replica.sh
    command: --server-id=2 --relay-log=relay-bin --read-only=1

